from .aceshop import AceShop
from .armspeed import ArmSpeed
from .dgshop import DgShop
from .discconnection import Discconnection
from .discexpress import DiscExpress
from .discgolfbagbuilder import DiscgolfBagBuilder
from .discimport import DiscImport
from .discmania import Discmania
from .discrepublic import Discrepublic
from .discsport import Discsport
from .frisbeefeber import FrisbeeFeber
from .fyndisc import Fyndisc
from .wearediscgolf import WeAreDiscgolf
from .kastmeg import Kastmeg
from .krokholdgs import Krokholdgs
from .latitude64 import Latitude64
from .pdga import Pdga
from .rocketdiscs import RocketDiscs
from .sunesport import SuneSport
from .xxl import Xxl
